author: 'Buzurgmehr Arjmandi'
name: 'SARIF Converter'
description: 'Convert SARIF files to other formats using sarif-converter.'
inputs:
  sarif:
    description: 'Path (relative to the runner temp) to the source SARIF file.'
    required: true
  output:
    description: 'Path (relative to runner temp) where the converted file will be written.'
    required: true
  type:
    description: 'Output format passed to sarif-converter via --type.'
    default: 'html'
  image:
    description: 'Docker image to use. Defaults to latest'
    required: false
    default: 'ghcr.io/b-zurg/sarif-converter:latest'
runs:
  using: 'composite'
  steps:
    - name: Pull converter image
      run: docker pull "${{ inputs.image }}"
      shell: bash

    - name: Run SARIF converter
      run: |
        docker run --rm \
          -v "$GITHUB_WORKSPACE:$GITHUB_WORKSPACE" \
          -v "$RUNNER_TEMP:$RUNNER_TEMP" \
          -w "$GITHUB_WORKSPACE" \
          "${{ inputs.image }}" \
          --type "${{ inputs.type }}" \
          "${{ inputs.sarif }}" \
          "${{ inputs.output }}"
      shell: bash
branding:
  icon: 'crosshair'
  color: 'orange'