name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
  contents: read
  packages: write

jobs:
  publish-dev-image:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - name: Read version
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          
      - name: Check version bump
        uses: rayepps/require-semver-bump@v1
        with:
          github-token: ${{ github.token }}
          file: ./VERSION
          pattern: '^\s*([0-9]+\.[0-9]+\.[0-9]+)\s*$'

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push PR image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sarif-converter:dev-${{ steps.version.outputs.version }}

      - name: Convert sample SARIF using PR image
        run: |
          docker run --rm \
            -v "$PWD:$PWD" \
            -w "$PWD" \
            ghcr.io/${{ github.repository_owner }}/sarif-converter:dev-${{ steps.version.outputs.version }} \
            --type html \
            testdata/sample.sarif \
            testdata/sample.html

      - name: Verify PR image output produced
        run: test -s testdata/sample.html
