name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  issues: read
  pull-requests: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and tag
        id: bump
        uses: jefflinse/pr-semver-bump@v1.6.0
        with:
          mode: bump
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          major-label: major
          minor-label: minor
          patch-label: patch

      - name: Log in to GHCR
        if: steps.bump.outputs.skipped != 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push release image
        if: steps.bump.outputs.skipped != 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/sarif-converter:latest
            ghcr.io/${{ github.repository_owner }}/sarif-converter:${{ steps.bump.outputs.version }}
