name: Tag Release

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  create-release-tag:
    if: github.ref_type == 'branch' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            version:
              - 'VERSION'

      - name: Read version
        id: version
        run: |
          VERSION=$(tr -d "\n\r" < VERSION)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Tag release if VERSION changed
        if: steps.changes.outputs.version == 'true'
        env:
          TAG: ${{ steps.version.outputs.version }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin --tags
          if git rev-parse "refs/tags/$TAG" >/dev/null 2>&1 || \
             git ls-remote --exit-code --tags origin "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists; skipping"
            exit 0
          fi
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"
