name: Test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
  contents: read
  packages: write
  issues: read
  pull-requests: read

jobs:
  publish-dev-image:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - name: Validate release metadata
        uses: jefflinse/pr-semver-bump@v1.6.0
        with:
          mode: validate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          major-label: major
          minor-label: minor
          patch-label: patch
          noop-labels: no-bump

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push PR image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sarif-converter:dev-${{ github.event.pull_request.number }}

      - name: Convert sample SARIF using PR image
        run: |
          docker run --rm \
            -v "$PWD:$PWD" \
            -w "$PWD" \
            ghcr.io/${{ github.repository_owner }}/sarif-converter:dev-${{ github.event.pull_request.number }} \
            --type html \
            testdata/sample.sarif \
            testdata/sample.html

      - name: Verify PR image output produced
        run: test -s testdata/sample.html
